project:
  type: website
  output-dir: docs

website:
  title: "ENVS-193FE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



