project:
  type: website
  output-dir: docs

website:
  title: "ENVS 193FE"
  navbar:
    left:
      - href: https://docs.google.com/document/d/1jVpUYIQizC8bupuHlFO3Zw4Tomf8oa5hZm5wFW8XhrI/edit?usp=sharing
        text: Syllabus
      - href: assignments.qmd
        text: Assignments
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true



