---
title: "Methods of promoting observations"
description: "things to think about when conducting an observation"
format: html
---

:::{.callout-note title="Source credit"}
Much of the inspiration for note-taking and observation comes from common note-taking methods in ecological disciplines and John Muir Laws's _The Guide to Nature Drawing and Journaling_. If you're interested in borrowing this text, let me know!

The information on this page comes from two sources by John Muir Laws: _The Guide to Nature Drawing and Journaling_ and _Opening the World Through Nature Journaling._

If you're interested in developing your journaling practice further, I would highly recommend John Muir Laws's work! He has many free videos walking through observation techniques, drawing, composition, etc. 
:::

## Promoting observation

### I notice…
Examine whatever you are looking at. Start to say observations out loud. Do not filter anything out: if you see it, say it. Look at structure, behavior, color, interactions. Change your perspective: look up close or far away and see what else you can observe. If you find yourself running out of observations, challenge yourself to discover something new, or just say "I notice. . ." until an idea pops out. Pay attention to what surprises you. This gives you insight into
ways that the world is different than you had thought.

### I wonder…
After observing your object, start to come up with questions about it and say those out loud, too. Your questions might be connected to an observation you made earlier, or they could be about any aspect of what you're observing. There is no need to worry about answering the questions yet. Just get them all out there. It's okay if you continue to make-and say-observations as you come up with questions.

### It reminds me of…
Last, say out loud everything that your object reminds you of. Allow yourself to be uninhibited in this step. Say anything that comes to mind: the object may have jarred your memory, reminding you of an experience you've had or a piece of information you already know, or the way it looks physically might remind you of something. Try looking at individual parts of the object, then back up and examine it as a whole.

## Interrogatives

### Who: identity and identification
“Who made this nest?” “What kind of bird is that?”

### What: describing events, trends, phenomena, behaviors
"What foraging strategies is this bird using?" "What is happening here?" "What happens when the sun comes out?"

### Where: location (local and large scale)
"Do I spot this species at the forest edge or deep in the woods?" "Is this bird a resident or is it migrating?" "Where is it going next?" "Where will it spend the night?" "Is this nest hole oriented for protection from the wind or water?"

When: timing and phenology
"What part of the nesting cycle are we in?" "How does the approaching winter play into what the bird is doing right now?" "How long can this cormorant hold its breath?" "How long does it take for the newt to crawl over a log?” “When did the flower turn into the fruit?”

### How: mechanism or process
“How do those pelicans fly so close to the water without hitting the surface?” “How do bustits weave such delicate nests?”

### Why: reason or meaning
“Why are the wings tilted up?” “Why are the leaves glossy?” “Why are these two individuals growing in such different locations?”

 “Why” questions can be asked of any observation and are a good follow-up to other questions, to push inquiry deeper.
