---
title: "Site selection"
date: 2026-10-02
---

[Due Friday 2 October at 11:59 PM on Canvas]{style="color: #BE5A47; font-size: 24px;"}  

## Project overview

This is the first of five project prep assignments for the **field guide** assignment. Your final field guide will be a guide to the 5 most common species in a given taxonomic group at the site of your choosing.

## Assignment

### 1. Familiarize yourself with the sites we will visit in this class.

You can find a list of sites on the syllabus and on the site selection spreadsheet.

### 2. Sign up for _two_ site × taxonomic group combinations.

For this and following steps, you will explore your options for two site × taxonomic group combinations. Your selections are _not_ set in stone; however, you should give yourself the flexibility to explore two groups to ultimately choose one later on.

### 3. Articulate your reasoning for your choices.

In 1-2 sentences, describe:

- why you are interested in these sites, with specific references to your own interests in ecosystems, experience, etc.
- why you are interested in these taxonomic groups, again with specific references to your own interests
- why you want to explore the taxonomic groups you chose at the sites you chose
- how you personally might be able to transport yourself to these sites, if you needed to visit them (e.g. via bus, car, etc.) - be realistic about this!

## Checklist

By the due date, you should have:

- [ ] signed up for _two_ site × taxonomic group combinations
- [ ] addressed the points in part 3










