---
title: "Detailed outline"
date: 2026-10-13
---

[Hard copy due at the beginning of class on Tuesday 13 October]{style="color: #D95204; font-size: 28px;"} 

## Overview

This is the third of four project prep assignments for the **field guide** assignment. Previously, you drew multiple interaction diagrams and hypothesized about the potential interactions between species in your focal taxonomic group. In this assignment, you will create a detailed outline of the layout and the text for your field guide.

To have some flexibility in layout, this assignment may be done digitally _or_ by hand. If you choose to complete your assignment digitally, make sure to factor in the time to print it out. [Note that your final field guide must be hand made and written.]{style="color: #D95204; font-weight: bold"} 

:::{.callout-note title="Free printing resources on campus"}
Use [GauchoPrint](https://it.ucsb.edu/services/student-services/printing) to print for free!
:::

## Before starting this assignment

### Read the final field guide requirements.

Make sure you understand the components you will need to incorporate for your field guide.

:::{.callout-note title="Choose your site × taxonomic group!"}
In the last assignment, you explored potential relationships between species in your chosen taxonomic group at your site. Before proceeding, _choose one_ with which to move forward.
:::

## Assignment

### 1. Create a mock up of the layout.

In your choice of medium (e.g. Canva, Google Slides, Word doc, pen and paper), create a mock layout of all the pages in your field guide. Use boxes or other shapes to denote areas of the page in which you intend to place an image or text. Label any shapes with what will occupy that space.

Keep in mind that:

- you are not locked into the layout you create here; this is meant for you to be able to visualize your field guide prior to starting the final draft.
- you do not need to create full page layouts for each page of your field guide; feel free to use half size pages.

### 2. Outline the text. 

:::{.callout-tip title="Differences between an outline and a draft"}
**Outlined text** is in bullet points representing ideas that you will eventually express in full sentences in a **draft**. The outline you create here will be the foundation off of which you build your first draft (due next week). 

In this assignment, you are expected to have text in _bullet point form_.
:::

Outline the text for each species entry. For each of the species you have chosen for your field guide, you should have bullet points outlining the:

- [ ] species description
- [ ] habitat description
- [ ] ecological description
- [ ] some citations (these don't have to be full citations; you're just providing basic information on the sources from which you are pulling this information)

:::{.callout-note title="How many bullet points do I need for each section?"}
Unfortunately, this depends. You should have enough information in your outline to receive feedback; thus, your bulleted ideas should be clear enough such that someone (An) can read your outline to give you comments, but be unstructured and flexible enough to change.
:::

:::{.callout-note title="Finding sources of information"}
You can use published books or peer-reviewed articles as sources. Existing field guides are great places to start! 

You can also look at citations from species pages. iNaturalist pages have lots of cited peer-reviewed papers. For example, this iNaturalist page for the [North American Mountain Lion](https://www.inaturalist.org/taxa/143589-Puma-concolor-couguar) has all the sources listed at the bottom. While not all sources may be relevant to you, you can use these as starting points to find your own information.
:::

### 3. Describe how you plan to incorporate visuals.

Each species entry should have a visual representation of the species. In 1-3 sentences, describe how you plan to create your visuals (e.g. photograph organisms yourself, draw, paint).

## Checklist

By the due date, you should have:

- [ ] a layout of all the pages in your field guide from part 1
- [ ] an outline of your species entries from part 2
- [ ] written response to part 3

As a reminder: [this assignment may be done digitally or by hand.]{style="color: #D95204; font-weight: bold"} You will turn in the paper copy of your work in class on Tuesday.
